// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/rubentanahara/user_service/internal/logging"
	"github.com/rubentanahara/user_service/internal/user"
	"io"
	"os"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*Server, func(), error) {
	mongoURI := provideMongoURI()
	maxPoolSize, err := provideMaxPoolSize()
	if err != nil {
		return nil, nil, err
	}
	client, cleanup, err := provideMongoClient(ctx, mongoURI, maxPoolSize)
	if err != nil {
		return nil, nil, err
	}
	mongoDBName := provideMongoDBName()
	collection, err := provideUsersCollection(ctx, client, mongoDBName)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repository := user.NewMongoRepository(collection)
	service := user.NewService(repository)
	writer := provideLogOutput()
	logger := logging.NewLogger(writer)
	jwtSecret, err := provideJWTSecret()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tokenIssuer := provideTokenIssuer(jwtSecret)
	handler := user.NewHandler(service, logger, tokenIssuer)
	port := providePort()
	server := NewServer(handler, logger, client, port)
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideLogOutput() io.Writer {
	return os.Stdout
}
